import { QueryRouteDefinition, RetrievalPolicy, RouteId } from "@/ai/contracts/router";

export const BASELINE_RETRIEVAL_POLICIES: Record<string, RetrievalPolicy> = {
  "policy-broad": {
    id: "policy-broad",
    name: "Broad Portfolio Retrieval",
    description: "Balanced multi-source candidate generation across all portfolio assets",
    sourceTypes: undefined, // All sources
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 15,
    sparseTopK: 15,
    candidateCap: 20,
    rrfK: 60,
    isDefault: true,
  },
  "policy-project": {
    id: "policy-project",
    name: "Project-Scoped Retrieval",
    description: "Deep dive candidate generation targeting published projects and case studies",
    sourceTypes: ["project"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 12,
    sparseTopK: 12,
    candidateCap: 15,
    rrfK: 60,
  },
  "policy-cv-experience": {
    id: "policy-cv-experience",
    name: "CV & Experience Retrieval",
    description:
      "High-precision retrieval targeting career milestones, roles, and verified resume sections",
    sourceTypes: ["cv"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 10,
    sparseTopK: 10,
    candidateCap: 10,
    rrfK: 60,
  },
  "policy-skills": {
    id: "policy-skills",
    name: "Skills & Technical Competencies",
    description: "Retrieval targeting tech stack proficiencies, tools, and project-proven skills",
    sourceTypes: ["cv", "project", "block"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 12,
    sparseTopK: 12,
    candidateCap: 15,
    rrfK: 60,
  },
  "policy-profile": {
    id: "policy-profile",
    name: "Profile & Persona Retrieval",
    description: "Focuses on bio, introduction, philosophical approach, and core background",
    sourceTypes: ["section", "block", "cv"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 10,
    sparseTopK: 10,
    candidateCap: 10,
    rrfK: 60,
  },
  "policy-technical": {
    id: "policy-technical",
    name: "Technical Details & Architecture",
    description: "Code, system design, data flow, and algorithmic implementation candidates",
    sourceTypes: ["project", "block"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 15,
    sparseTopK: 15,
    candidateCap: 15,
    rrfK: 60,
  },
  "policy-job-fit": {
    id: "policy-job-fit",
    name: "Job Fit & Alignment",
    description:
      "Comprehensive evidence collection matching role requirements against portfolio achievements",
    sourceTypes: ["cv", "project"],
    denseEnabled: true,
    sparseEnabled: true,
    denseTopK: 20,
    sparseTopK: 20,
    candidateCap: 25,
    rrfK: 60,
  },
};

export const BASELINE_QUERY_ROUTES: Record<RouteId, QueryRouteDefinition> = {
  profile: {
    id: "profile",
    label: "Profile & Identity",
    description: "Questions regarding who Anas is, biography, background, and persona",
    retrievalPolicyId: "policy-profile",
    needsRewrite: true,
    keywords: {
      ar: ["من هو", "نبذة", "عن انس", "التعريف", "الخلفية", "الهوية", "شخصية", "سيرة شخصية"],
      en: [
        "who is",
        "about anas",
        "bio",
        "biography",
        "background",
        "profile",
        "introduction",
        "tell me about",
      ],
    },
  },
  project: {
    id: "project",
    label: "Projects & Applications",
    description:
      "Specific projects, applications, portfolio highlights, and software implementations",
    retrievalPolicyId: "policy-project",
    needsRewrite: true,
    keywords: {
      ar: ["مشروع", "مشاريع", "اعمال", "اعمالك", "تطبيقات", "تطبيق", "نماذج", "مستودع", "كود"],
      en: [
        "project",
        "projects",
        "portfolio",
        "built",
        "apps",
        "application",
        "github",
        "repo",
        "demo",
      ],
    },
  },
  skills: {
    id: "skills",
    label: "Skills & Tech Stack",
    description: "Programming languages, frameworks, AI libraries, and technical toolchains",
    retrievalPolicyId: "policy-skills",
    needsRewrite: true,
    keywords: {
      ar: ["مهارات", "تقنيات", "لغات البرمجة", "ادوات", "اتقان", "مكدس", "اطر عمل", "خبرة تقنية"],
      en: [
        "skill",
        "skills",
        "technologies",
        "tech stack",
        "languages",
        "frameworks",
        "tools",
        "libraries",
        "proficient",
      ],
    },
  },
  experience: {
    id: "experience",
    label: "Work Experience & Career",
    description: "Employment history, companies, roles, career milestones, and seniority",
    retrievalPolicyId: "policy-cv-experience",
    needsRewrite: true,
    keywords: {
      ar: ["خبرة", "خبرات", "تاريخ مهني", "مسيرة", "شركات", "وظائف", "سجل العمل", "عملت", "مناصب"],
      en: [
        "experience",
        "work history",
        "career",
        "companies",
        "roles",
        "senior",
        "positions",
        "employment",
      ],
    },
  },
  certification: {
    id: "certification",
    label: "Certifications & Education",
    description: "Degrees, academic credentials, professional certificates, and courses",
    retrievalPolicyId: "policy-cv-experience",
    needsRewrite: true,
    keywords: {
      ar: ["شهادة", "شهادات", "اعتمادات", "مؤهلات", "درجة", "تعليم", "جامعة", "دورات"],
      en: [
        "certification",
        "certifications",
        "certified",
        "credentials",
        "degrees",
        "education",
        "university",
        "courses",
      ],
    },
  },
  technical_detail: {
    id: "technical_detail",
    label: "Architecture & Technical Deep Dive",
    description:
      "Algorithmic design, system architecture, benchmarks, and deep technical mechanisms",
    retrievalPolicyId: "policy-technical",
    needsRewrite: true,
    keywords: {
      ar: [
        "معمارية",
        "خوارزميات",
        "تفاصيل تقنية",
        "تنفيذ",
        "بنية النظام",
        "اداء",
        "قواعد بيانات",
        "تضمين",
        "بحث هجين",
      ],
      en: [
        "architecture",
        "algorithm",
        "technical details",
        "implementation",
        "pipeline",
        "benchmarks",
        "system design",
        "latency",
      ],
    },
  },
  job_fit: {
    id: "job_fit",
    label: "Job Fit & JD Matching",
    description: "Matching specific job requirements or role descriptions to Anas's qualifications",
    retrievalPolicyId: "policy-job-fit",
    needsRewrite: true,
    keywords: {
      ar: [
        "ملائمة وظيفية",
        "مطابقة الوظيفة",
        "هل يناسب",
        "مؤهل لوظيفة",
        "متطلبات",
        "توظيف",
        "هل يمكنك تولي",
      ],
      en: [
        "job fit",
        "match",
        "suitable for",
        "hire",
        "hiring",
        "requirements",
        "fit for",
        "candidate for",
        "qualify",
      ],
    },
  },
  cv: {
    id: "cv",
    label: "Curriculum Vitae / Resume",
    description: "Requests for resume overview, CV document, or downloadable career summaries",
    retrievalPolicyId: "policy-cv-experience",
    needsRewrite: false,
    keywords: {
      ar: ["سيرة ذاتية", "تحميل السيرة", "ملف الـ cv", "ملخص السيرة", "رزنامة", "بي دي اف", "pdf"],
      en: [
        "cv",
        "resume",
        "curriculum vitae",
        "download cv",
        "resume pdf",
        "get cv",
        "view resume",
      ],
    },
  },
  broad_portfolio: {
    id: "broad_portfolio",
    label: "Broad Portfolio Overview",
    description: "General exploratory queries, greetings, or wide-ranging portfolio questions",
    retrievalPolicyId: "policy-broad",
    needsRewrite: true,
    keywords: {
      ar: ["محفظة", "عام", "كل شيء", "ماذا تستطيع", "استعراض", "مرحبا", "اهلا", "السلام عليكم"],
      en: [
        "portfolio",
        "overview",
        "everything",
        "what can you do",
        "general",
        "show me",
        "hello",
        "hi",
        "hey",
      ],
    },
  },
};
