import type { FeatureFlag } from "../domain/feature-flags";

export const BASELINE_FEATURE_FLAGS: FeatureFlag[] = [
  {
    key: "ai.query_rewriting",
    isEnabled: true,
    description: "Multi-query expansion and contextual rewriting to maximize retrieval recall.",
    category: "ai",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "ai.reranker",
    isEnabled: true,
    description: "Neural cross-encoder reranking to elevate top semantic candidate passages.",
    category: "ai",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "ai.streaming_chat",
    isEnabled: true,
    description: "Server-sent events streaming for real-time portfolio AI assistant responses.",
    category: "ai",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "ai.lab_interactive",
    isEnabled: true,
    description: "Public interactive AI demonstrations configured from the control plane.",
    category: "ai",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "ai.eval_public_dashboard",
    isEnabled: true,
    description: "Public transparency page showcasing golden evaluation benchmark metrics.",
    category: "ai",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "security.rate_limiting",
    isEnabled: true,
    description: "Active IP and fingerprint rate limiting to protect public endpoints from abuse.",
    category: "security",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "ui.inline_admin_edit",
    isEnabled: true,
    description: "Inline edit triggers adjacent to dynamic portfolio elements for authenticated admins.",
    category: "ui",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "perf.cache_tags",
    isEnabled: true,
    description: "Tag and key-based caching strategy with granular surgical invalidation.",
    category: "performance",
    targetRolloutPercentage: 100,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "experimental.voice_chat",
    isEnabled: false,
    description: "Experimental voice input and speech synthesis in portfolio AI chat.",
    category: "experimental",
    targetRolloutPercentage: 0,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    key: "experimental.deep_research",
    isEnabled: false,
    description: "Autonomous multi-source deep inquiry synthesis for complex technical questions.",
    category: "experimental",
    targetRolloutPercentage: 0,
    updatedAt: "2026-09-18T00:00:00.000Z",
  },
];
