import type { AuditEventRecord, AuditLogSummary } from "../domain/audit-log";

export const BASELINE_AUDIT_EVENTS: AuditEventRecord[] = [
  {
    id: "aud-001-sys-init",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "system_init",
    entityType: "system",
    entityId: "core",
    previousState: null,
    newState: { version: "1.0.0", environment: "production", featuresLoaded: 50 },
    ipAddress: "127.0.0.1",
    userAgent: "Antigravity/AgenticCLI",
    createdAt: "2026-09-18T12:00:00.000Z",
  },
  {
    id: "aud-002-model-assign",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "model_assignment",
    entityType: "model",
    entityId: "mod-gpt4o-1",
    previousState: { capability: "generation", modelId: "mod-gpt-4o-mini" },
    newState: { capability: "generation", modelId: "mod-gpt4o-1", status: "active" },
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    createdAt: "2026-09-18T14:30:00.000Z",
  },
  {
    id: "aud-003-prompt-pub",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "prompt_publish",
    entityType: "prompt",
    entityId: "system_chat",
    previousState: { versionNumber: 1, isCurrent: true },
    newState: { versionNumber: 2, isCurrent: true, changelog: "Added strict anti-hallucination instruction" },
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    createdAt: "2026-09-18T15:45:00.000Z",
  },
  {
    id: "aud-004-cv-publish",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "cv_publish",
    entityType: "cv",
    entityId: "cv-pub-current",
    previousState: { versionNumber: 1, isCurrent: true },
    newState: { versionNumber: 2, isCurrent: true, fileName: "Anas_Al_Najjar_AI_Engineer_CV.pdf" },
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    createdAt: "2026-09-18T16:20:00.000Z",
  },
  {
    id: "aud-005-reindex",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "reindex",
    entityType: "rag",
    entityId: "v1.0.0-bge-m3",
    previousState: { totalChunks: 64 },
    newState: { totalChunks: 82, status: "completed", denseDimension: 1024 },
    ipAddress: "127.0.0.1",
    userAgent: "System/ScheduledWorker",
    createdAt: "2026-09-18T17:00:00.000Z",
  },
  {
    id: "aud-006-secret-update",
    userId: "usr-admin-system-root",
    userEmail: "admin@anas.dev",
    action: "secret_update",
    entityType: "secret",
    entityId: "ai_provider_openai_key",
    previousState: null,
    newState: { key: "ai_provider_openai_key", maskedPreview: "sk-***1234", action: "[REDACTED]" },
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    createdAt: "2026-09-18T17:30:00.000Z",
  },
];

export const BASELINE_AUDIT_SUMMARY: AuditLogSummary = {
  totalEvents: 6,
  securityEventsCount: 3,
  actionsBreakdown: {
    system_init: 1,
    model_assignment: 1,
    prompt_publish: 1,
    cv_publish: 1,
    reindex: 1,
    secret_update: 1,
  },
  entityTypesBreakdown: {
    system: 1,
    model: 1,
    prompt: 1,
    cv: 1,
    rag: 1,
    secret: 1,
  },
  recentEvents: BASELINE_AUDIT_EVENTS,
};
