import type { Locale } from "@/i18n/config";

/** Admin interface copy (not editable from the site itself). */
const en = {
  editMode: "Edit mode",
  editOn: "Editing on",
  editOff: "Editing off",
  dashboard: "Dashboard",
  viewSite: "View site",
  signOut: "Sign out",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  cancel: "Cancel",
  close: "Close",
  delete: "Delete",
  deleteConfirm: "Delete this item? You can restore it later from its history.",
  hide: "Hide",
  show: "Publish",
  moveUp: "Move up",
  moveDown: "Move down",
  edit: "Edit",
  add: "Add",
  english: "English",
  arabic: "Arabic",
  shared: "Shared (both languages)",
  translateToAr: "Translate English → Arabic",
  translateToEn: "Translate Arabic → English",
  translating: "Translating…",
  resetDefault: "Reset to default",
  status: "Status",
  published: "Published",
  draft: "Draft",
  hidden: "Hidden",
  history: "History",
  restore: "Restore",
  upload: "Upload",
  uploading: "Uploading…",
  replace: "Replace",
  remove: "Remove",
  orPasteUrl: "or paste a link",
  listHint: "One item per line",
  tagsHint: "Separate with commas",
  textKey: "Interface text",
  error: "Something went wrong",
  reindexNote: "Saved. The AI assistant is learning the change now.",
  uploadCv: "Upload new CV (PDF)",
  cvUploaded: "CV uploaded. The assistant is reading it now (this can take up to a minute).",
  notAdmin: "Your session expired. Sign in again.",
  slug: "URL name",
};

export type AdminStrings = Record<keyof typeof en, string>;

const ar: AdminStrings = {
  editMode: "وضع التعديل",
  editOn: "التعديل مفعّل",
  editOff: "التعديل متوقف",
  dashboard: "لوحة التحكم",
  viewSite: "عرض الموقع",
  signOut: "تسجيل الخروج",
  save: "حفظ",
  saving: "عم يحفظ…",
  saved: "تم الحفظ",
  cancel: "إلغاء",
  close: "إغلاق",
  delete: "حذف",
  deleteConfirm: "حذف هذا العنصر؟ بتقدر ترجعه بعدين من السجل.",
  hide: "إخفاء",
  show: "نشر",
  moveUp: "لفوق",
  moveDown: "لتحت",
  edit: "تعديل",
  add: "إضافة",
  english: "الإنجليزية",
  arabic: "العربية",
  shared: "مشترك (للغتين)",
  translateToAr: "ترجمة من الإنجليزية للعربية",
  translateToEn: "ترجمة من العربية للإنجليزية",
  translating: "عم يترجم…",
  resetDefault: "رجوع للنص الأصلي",
  status: "الحالة",
  published: "منشور",
  draft: "مسودة",
  hidden: "مخفي",
  history: "السجل",
  restore: "استرجاع",
  upload: "رفع",
  uploading: "عم يرفع…",
  replace: "استبدال",
  remove: "إزالة",
  orPasteUrl: "أو الصق رابط",
  listHint: "كل عنصر بسطر",
  tagsHint: "افصل بفاصلة",
  textKey: "نص الواجهة",
  error: "صار خطأ",
  reindexNote: "تم الحفظ. المساعد الذكي عم يتعلم التعديل هلأ.",
  uploadCv: "رفع سيرة ذاتية جديدة (PDF)",
  cvUploaded: "تم رفع السيرة الذاتية. المساعد عم يقرأها هلأ (ممكن تاخد لحد دقيقة).",
  notAdmin: "انتهت الجلسة. سجّل دخول من جديد.",
  slug: "اسم الرابط",
};

export function adminStrings(locale: Locale): AdminStrings {
  return locale === "ar" ? ar : en;
}
