import type { NavigationItem } from "../domain/types";

export const DEFAULT_NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: "nav-projects",
    destinationType: "internal",
    target: "/projects",
    labelKey: "nav.projects",
    iconKey: "folder-git-2",
    orderIndex: 10,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-experience",
    destinationType: "internal",
    target: "/experience",
    labelKey: "nav.experience",
    iconKey: "briefcase",
    orderIndex: 20,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-cv",
    destinationType: "internal",
    target: "/cv",
    labelKey: "nav.cv",
    iconKey: "file-text",
    orderIndex: 30,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-about",
    destinationType: "internal",
    target: "/about",
    labelKey: "nav.about",
    iconKey: "user",
    orderIndex: 40,
    isVisible: false,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-contact",
    destinationType: "internal",
    target: "/contact",
    labelKey: "nav.contact",
    iconKey: "mail",
    orderIndex: 50,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-ai-chat",
    destinationType: "internal",
    target: "/chat",
    labelKey: "nav.ask_about_anas",
    iconKey: "sparkles",
    orderIndex: 60,
    isVisible: false,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-admin",
    destinationType: "internal",
    target: "/admin",
    labelKey: "nav.admin",
    iconKey: "layout-dashboard",
    orderIndex: 90,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "admin_only",
    placement: "header",
  },
];
