import type { NavigationItem } from "../domain/types";

export const DEFAULT_NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: "nav-projects",
    destinationType: "internal",
    target: "/projects",
    labelKey: "nav.projects",
    iconKey: "folder-git-2",
    orderIndex: 10,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-cv",
    destinationType: "internal",
    target: "/cv",
    labelKey: "nav.cv",
    iconKey: "file-text",
    orderIndex: 20,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-ai-chat",
    destinationType: "internal",
    target: "/chat",
    labelKey: "nav.ai_chat",
    iconKey: "sparkles",
    orderIndex: 30,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
    badge: "RAG",
  },
  {
    id: "nav-job-fit",
    destinationType: "internal",
    target: "/job-fit",
    labelKey: "nav.job_fit",
    iconKey: "briefcase",
    orderIndex: 40,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-lab",
    destinationType: "internal",
    target: "/lab",
    labelKey: "lab.nav.link",
    iconKey: "flask-conical",
    orderIndex: 45,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-evaluation",
    destinationType: "internal",
    target: "/evaluation",
    labelKey: "eval.nav.link",
    iconKey: "chart-bar",
    orderIndex: 48,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "all",
    placement: "both",
  },
  {
    id: "nav-admin",
    destinationType: "internal",
    target: "/admin",
    labelKey: "nav.admin",
    iconKey: "layout-dashboard",
    orderIndex: 90,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "admin_only",
    placement: "header",
  },
  {
    id: "nav-sign-in",
    destinationType: "internal",
    target: "/sign-in",
    labelKey: "nav.sign_in",
    iconKey: "log-in",
    orderIndex: 100,
    isVisible: true,
    openInNewTab: false,
    authVisibility: "guests_only",
    placement: "header",
  },
];
